name: ibc
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - absl-py=0.15.0
  - anyio=3.5.0
  - argcomplete=1.12.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - cffi=1.15.0
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - cloudpickle=2.0.0
  - cryptography=36.0.0  
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.10.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - ffmpeg=4.3
  - fonttools=4.25.0
  - freetype=2.11.0
  - fsspec=2022.1.0
  - gds-tools=1.5.0.59
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - imagecodecs=2021.8.26
  - importlib_metadata=4.11.3
  - intel-openmp=2019.4
  - ipykernel=6.4.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.0.2
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter_client=7.1.2
  - jupyter_core=4.9.1
  - jupyter_server=1.13.5
  - jupyterlab=3.2.9
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jxrlib=1.1
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=3.0
  - libaec=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.5.0.59
  - libcufile-dev=1.5.0.59
  - libcurand=10.3.1.50
  - libcurand-dev=10.3.1.50
  - libcurl=7.80.0
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libiconv=1.15
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libmklml=2019.0.5
  - libnghttp2=1.46.0
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.1.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.0
  - libzopfli=1.0.3
  - llvm-openmp=12.0.1
  - locket=0.2.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - munkres=1.1.4
  - nbclassic=0.3.5
  - nbclient=0.5.11
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - nettle=3.7.3
  - networkx=2.6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - notebook=6.4.8
  - nsight-compute=2022.4.0.15
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1s
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.2
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.11
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2021.3
  - pywavelets=1.1.1
  - pyyaml=6.0
  - pyzmq=22.3.0
  - readline=8.1.2
  - requests=2.27.1
  - scikit-image=0.18.3
  - scipy=1.6.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - sqlite=3.37.2
  - terminado=0.13.1
  - testpath=0.5.0
  - tifffile=2021.7.2
  - tk=8.6.11
  - toolz=0.11.2  
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - antlr4-python3-runtime==4.9.3
    - bsuite==0.3.5
    - cached-property==1.5.2
    - cachetools==5.0.0
    - colorednoise==2.1.0
    - cython==0.29.28
    - descartes==1.1.0
    - dm-control==1.0.9
    - dm-env==1.6
    - dm-tree==0.1.8
    - fasteners==0.17.3
    - frozendict==2.3.4
    - future==0.18.2
    - glfw==2.5.0
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - gym==0.22.0
    - gym-notices==0.0.4
    - gym-robotics==0.1.0
    - h5py==3.6.0
    - hydra-core==1.2.0
    - hydra-joblib-launcher==1.2.0
    - imageio==2.16.0
    - imageio-ffmpeg==0.4.5
    - importlib-metadata==4.11.1
    - importlib-resources==5.7.1
    - ipdb==0.13.9
    - joblib==1.1.0
    - kornia==0.6.3
    - labmaze==1.0.5
    - lxml==4.8.0
    - markdown==3.3.6    
    - mizani==0.7.3
    - mujoco==2.3.1.post1
    - mujoco-py==2.1.2.14
    - numpy==1.21.5
    - oauthlib==3.2.0
    - omegaconf==2.2.1
    - palettable==3.3.0
    - pandas==1.3.5
    - patsy==0.5.3
    - plotnine==0.8.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyopengl==3.1.6
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-learn==1.0.2
    - seaborn==0.11.2
    - sklearn==0.0
    - stats==0.1.2a0
    - statsmodels==0.13.5
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - toml==0.10.2    
    - tqdm==4.62.3
    - umap==0.1.1
    - werkzeug==2.0.3
    - xvfbwrapper==0.2.9
    - yapf==0.32.0