# NOTE : 
# You should make config/paths/config_path.yaml as following format
# The paths in this file should be different among the machines. 
# It should not be uploaded in github remote.
default_save_path_prefix : your path for saving the logging
workspace_path : this repository's path